version: '3'

services:
  postgres:
    container_name: discipline-postgres
    image: postgres
    shm_size: '4gb'
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 6010:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  mongo:
    image: mongo
    container_name: discipline-mongo
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    ports:
      - 6011:27017

volumes:
  postgres:
    driver: local
  mongo:
    driver: local