version: '3'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: discipline-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 6010:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local