version: '3'

services:
  mongo:
    image: mongo
    container_name: discipline-mongo
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    ports:
      - 6011:27017

volumes:
  mongo:
    driver: local