// <auto-generated />

using discipline.activity_scheduler.shared.infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using discipline.hangfire.infrastructure.DAL;

#nullable disable

namespace discipline.hangfire.infrastructure.DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250910170612_AddedAccounts")]
    partial class AddedAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("discipline.activity-scheduler.domain.Accounts.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("AccountId");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
