// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using discipline.hangfire.add_planned_tasks.DAL;

#nullable disable

namespace discipline.hangfire.add_planned_tasks.DAL.Migrations
{
    [DbContext(typeof(AddPlannedTaskDbContext))]
    partial class AddPlannedTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("planned-tasks")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("discipline.hangfire.add_planned_tasks.Models.PlannedTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ActivityRuleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("ActivityRuleId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsActivityCreated")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActivityCreated");

                    b.Property<bool>("IsPlannedEnable")
                        .HasColumnType("boolean")
                        .HasColumnName("IsPlannedEnable");

                    b.Property<DateOnly>("PlannedFor")
                        .HasColumnType("date")
                        .HasColumnName("PlannedFor");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("PlannedTasks", "planned-tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
