// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using discipline.hangfire.infrastructure.DAL;

#nullable disable

namespace discipline.hangfire.infrastructure.DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250910170702_AddedActivityRules")]
    partial class AddedActivityRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("discipline.hangfire.domain.Accounts.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("AccountId");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("discipline.hangfire.domain.ActivityRules.ActivityRule", b =>
                {
                    b.Property<string>("ActivityRuleId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("ActivityRuleId");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("AccountId");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Mode");

                    b.PrimitiveCollection<int[]>("SelectedDays")
                        .HasColumnType("integer[]")
                        .HasColumnName("SelectedDays");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Title");

                    b.HasKey("ActivityRuleId");

                    b.ToTable("ActivityRules", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
