// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using discipline.hangfire.infrastructure.DAL;

#nullable disable

namespace discipline.hangfire.infrastructure.DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250910171005_AddedAccountViewModel")]
    partial class AddedAccountViewModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("discipline.hangfire.domain.Accounts.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("AccountId");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("discipline.hangfire.domain.ActivityRules.ActivityRule", b =>
                {
                    b.Property<string>("ActivityRuleId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("ActivityRuleId");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("AccountId");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Mode");

                    b.PrimitiveCollection<int[]>("SelectedDays")
                        .HasColumnType("integer[]")
                        .HasColumnName("SelectedDays");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Title");

                    b.HasKey("ActivityRuleId");

                    b.ToTable("ActivityRules", (string)null);
                });

            modelBuilder.Entity("discipline.hangfire.domain.PlannedTasks.PlannedTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("AccountId");

                    b.Property<bool>("ActivityCreated")
                        .HasColumnType("boolean")
                        .HasColumnName("ActivityCreated");

                    b.Property<string>("ActivityRuleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("ActivityRuleId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("PlannedEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("PlannedEnable");

                    b.Property<DateOnly>("PlannedFor")
                        .HasColumnType("date")
                        .HasColumnName("PlannedFor");

                    b.HasKey("Id");

                    b.ToTable("PlannedTasks", (string)null);
                });

            modelBuilder.Entity("discipline.hangfire.shared.abstractions.ViewModels.AccountViewModel", b =>
                {
                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("AccountsView", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
