//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace discipline.centre.activityrules.api.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("discipline.centre.activityrules.api.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CreateActivityRule_NotUniqueTitle {
            get {
                return ResourceManager.GetString("CreateActivityRule.NotUniqueTitle", resourceCulture);
            }
        }
        
        internal static string UpdateActivityRule_ActivityRuleNotFound {
            get {
                return ResourceManager.GetString("UpdateActivityRule.ActivityRuleNotFound", resourceCulture);
            }
        }
        
        internal static string UpdateActivityRule_NotUniqueTitle {
            get {
                return ResourceManager.GetString("UpdateActivityRule.NotUniqueTitle", resourceCulture);
            }
        }
        
        internal static string CreateStageForActivityRule_ActivityRuleNotFound {
            get {
                return ResourceManager.GetString("CreateStageForActivityRule.ActivityRuleNotFound", resourceCulture);
            }
        }
        
        internal static string Validation_EmptyActivityRuleTitle {
            get {
                return ResourceManager.GetString("Validation.EmptyActivityRuleTitle", resourceCulture);
            }
        }
        
        internal static string Validation_ActivityRuleTitleTooLong {
            get {
                return ResourceManager.GetString("Validation.ActivityRuleTitleTooLong", resourceCulture);
            }
        }
        
        internal static string Validation_EmptyActivityRuleMode {
            get {
                return ResourceManager.GetString("Validation.EmptyActivityRuleMode", resourceCulture);
            }
        }
        
        internal static string Validation_NullDetails {
            get {
                return ResourceManager.GetString("Validation.NullDetails", resourceCulture);
            }
        }
        
        internal static string Validation_NullMode {
            get {
                return ResourceManager.GetString("Validation.NullMode", resourceCulture);
            }
        }
        
        internal static string ActivityRule_Details_EmptyTitle {
            get {
                return ResourceManager.GetString("ActivityRule.Details.EmptyTitle", resourceCulture);
            }
        }
        
        internal static string ActivityRule_Details_TitleTooLong {
            get {
                return ResourceManager.GetString("ActivityRule.Details.TitleTooLong", resourceCulture);
            }
        }
        
        internal static string ActivityRules_Mode_RuleModeRequireSelectedDays {
            get {
                return ResourceManager.GetString("ActivityRules.Mode.RuleModeRequireSelectedDays", resourceCulture);
            }
        }
        
        internal static string ActivityRule_Mode_SelectedDayOutOfRange {
            get {
                return ResourceManager.GetString("ActivityRule.Mode.SelectedDayOutOfRange", resourceCulture);
            }
        }
        
        internal static string ActivityRule_Stage_Title_EmptyValue {
            get {
                return ResourceManager.GetString("ActivityRule.Stage.Title.EmptyValue", resourceCulture);
            }
        }
        
        internal static string ActivityRule_Stage_Title_ValueTooLong {
            get {
                return ResourceManager.GetString("ActivityRule.Stage.Title.ValueTooLong", resourceCulture);
            }
        }
        
        internal static string ActivityRule_Stage_Index_ValueBelowOne {
            get {
                return ResourceManager.GetString("ActivityRule.Stage.Index.ValueBelowOne", resourceCulture);
            }
        }
        
        internal static string ActivityRule_Stages_StageTitleMustBeUnique {
            get {
                return ResourceManager.GetString("ActivityRule.Stages.StageTitleMustBeUnique", resourceCulture);
            }
        }
    }
}
