services:
  discipline-centre-hub:
    container_name: discipline-centre-hub
    build: 
      context: ./../discipline.centre
    ports:
      - 7001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    volumes:
      - ./../discipline.centre/src/Bootstrappers/discipline.centre.bootstrappers.api/Certs:/discipline/certs
    networks:
      - discipline-network

networks:
  discipline-network:
    driver: bridge