services:
  mongo:
    image: mongo
    container_name: discipline-mongo
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    ports:
      - 6011:27017
    networks:
      - discipline-network
  redis:
    image: redis
    container_name: discipline-redis
    restart: always
    ports:
      - 6012:6379
    volumes: 
      - cache:/data
    networks:
      - discipline-network
  postgres:
    image: postgres
    container_name: discipline-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpwd
    ports:
      - 6013:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - discipline-network
  jeager:
    image: jaegertracing/all-in-one:latest
    container_name: discipline-jaeger
    ports:
      - 6021:4317
      - 6022:16686
      - 6023:14250
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"

volumes:
  mongo:
    driver: local
  cache:
    driver: local
  postgres:
    driver: local

networks:
  discipline-network:
    driver: bridge